import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConnectkitProvider } from './components/connectkit-provider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConnectkitProvider>
        <body>{children}</body>
      </ConnectkitProvider>
    </html>
  );
}
